In [12]:
import pandas as pd 

df = pd.read_csv("/Users/sauravkarki/repos/college/cs207/java/STT5/courses_edited.csv")
df.head()

,Sl. No,Course code,Course name,Credits,L-T-P-S-C,Faculty,Department,Sections
0,Sem 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,Statistics,2.0,NaN,Dr. Ramesh Athe,DSAI,Combined
2,2,NaN,Introduction to DS and AI,2.0,NaN,Dr. Abdul Wahid,CSE,Combined
3,3,NaN,Open elective I,2.0,NaN,NaN,NaN,NaN
4,4,NaN,Probability,2.0,NaN,Dr. Lakshman,HSS,Combined